import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, Stack } from 'expo-router';
import { Screen } from '../src/components/Screen';
import { useMobileTheme } from '../src/components/theme';
import { MobileCloudRelayControlPlaneProfileSchema } from '../src/control-plane/profile';
import { mobileProfileStore, restoreActiveCloudAccountSession } from '../src/control-plane/runtime';
import { cloudMobileErrorMessage } from '../src/control-plane/cloud-error';
import { useI18n } from '../src/i18n';

export default function CloudControlPlanesScreen(){const{colors}=useMobileTheme();const{locale}=useI18n();const zh=locale==='zh-CN';const[items,setItems]=useState<any[]>([]);const[error,setError]=useState<string>();useEffect(()=>{void restoreActiveCloudAccountSession().then(session=>session.client.listControlPlanes()).then(setItems).catch(cause=>setError(cloudMobileErrorMessage(cause,zh)))},[zh]);
  async function add(entry:any){try{if(typeof entry.bindingId!=="string")throw Object.assign(new Error('Unsupported directory version'),{code:'CLOUD_DIRECTORY_BINDING_ID_UNSUPPORTED'});const session=await restoreActiveCloudAccountSession();const now=new Date().toISOString();const profile=MobileCloudRelayControlPlaneProfileSchema.parse({version:1,identity:{controlPlaneId:entry.controlPlaneId,publicKeyFingerprint:entry.publicKeyFingerprint,displayName:entry.displayName?.translations?.[locale]||entry.displayName?.default,protocolVersion:'2026-08-10'},access:{kind:'cloud-relay',serviceOrigin:session.origin,bindingId:entry.bindingId,bindingRevision:entry.bindingRevision,accountSession:session.reference(),transport:{request:true,stream:true,webSocket:true}},capabilities:{authentication:'required',aiSessions:true,nodes:true,instanceBoard:true,triggers:true,stories:true},createdAt:now,updatedAt:now});await mobileProfileStore.put(profile);router.replace('/(tabs)/(main)/inbox')}catch(cause){setError(cloudMobileErrorMessage(cause,zh))}}
  return <><Stack.Screen options={{title:zh?'选择 Control Plane':'Choose Control Plane'}}/><Screen><Pressable accessibilityRole="button" onPress={()=>router.push('/cloud-account-security' as never)}><Text style={[styles.accountLink,{color:colors.primary}]}>{zh?'Thandoff 账户设置':'Thandoff account settings'}</Text></Pressable><Text style={[styles.note,{color:colors.textMuted}]}>{zh?'目录只展示 Thandoff 账户绑定和中转状态。选择后可与同一 Control Plane 的直连配置并存。':'The directory contains only Thandoff account bindings and relay status. A Relay profile can coexist with a Direct profile for the same Control Plane.'}</Text>{items.map(entry=><Pressable accessibilityRole="button" key={entry.controlPlaneId} onPress={()=>void add(entry)} style={[styles.row,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.copy}><Text style={[styles.name,{color:colors.text}]}>{entry.displayName?.translations?.[locale]||entry.displayName?.default||entry.controlPlaneId}</Text><Text numberOfLines={1} style={[styles.fingerprint,{color:colors.textMuted}]}>{entry.publicKeyFingerprint}</Text></View><Text style={{color:entry.remoteAccess==='enabled'?colors.primary:colors.textMuted}}>{entry.remoteAccess}</Text></Pressable>)}{!items.length&&!error?<Text style={[styles.empty,{color:colors.textMuted}]}>{zh?'尚无已绑定的 Control Plane。':'No bound Control Planes.'}</Text>:null}{error?<Text accessibilityLiveRegion="polite" style={[styles.empty,{color:colors.error}]}>{error}</Text>:null}</Screen></>}
const styles=StyleSheet.create({accountLink:{fontSize:15,fontWeight:'600'},note:{fontSize:14,lineHeight:20},row:{alignItems:'center',borderRadius:8,borderWidth:StyleSheet.hairlineWidth,flexDirection:'row',gap:12,padding:14},copy:{flex:1,gap:4},name:{fontSize:16,fontWeight:'600'},fingerprint:{fontFamily:'monospace',fontSize:12},empty:{fontSize:14,padding:24,textAlign:'center'}});
