import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Alert, Linking, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, Stack } from 'expo-router';
import { NativeActionButton } from '../src/components/NativeActionButton';
import { OneTimeCodeInput } from '../src/components/OneTimeCodeInput';
import { Screen } from '../src/components/Screen';
import { useMobileTheme } from '../src/components/theme';
import { cloudMobileErrorMessage } from '../src/control-plane/cloud-error';
import { hasActiveCloudAccount, logoutActiveCloudAccount, restoreActiveCloudAccountSession } from '../src/control-plane/runtime';
import { useI18n } from '../src/i18n';

export default function CloudAccountSecurityScreen() {
  const { colors } = useMobileTheme(); const { locale } = useI18n(); const zh = locale === 'zh-CN';
  const [profile, setProfile] = useState<any>(); const [devices, setDevices] = useState<any[]>([]); const [providers, setProviders] = useState<any[]>([]);
  const [currentDeviceId, setCurrentDeviceId] = useState<string>();
  const [stepUp, setStepUp] = useState(''); const [stepCode, setStepCode] = useState(''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState('');
  const [enrollment, setEnrollment] = useState<any>(); const [totpCode, setTotpCode] = useState(''); const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string>();
  const load = useCallback(async () => { try { const session = await restoreActiveCloudAccountSession(); const [nextProfile, nextDevices, nextProviders] = await Promise.all([session.client.profile(), session.client.devices(), session.client.providers()]); setCurrentDeviceId(session.reference().id); setProfile(nextProfile); setDevices(nextDevices); setProviders(nextProviders); } catch (error) { setMessage(cloudMobileErrorMessage(error, zh)); } }, [zh]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); const subscription = Linking.addEventListener('url', () => void load()); return () => { clearTimeout(timer); subscription.remove(); }; }, [load]);
  async function action(operation: (client: any) => Promise<any>, done?: (result: any) => void) { setBusy(true); setMessage(undefined); try { const session = await restoreActiveCloudAccountSession(); const result = await operation(session.client); done?.(result); await load(); } catch (error) { setMessage(cloudMobileErrorMessage(error, zh)); } finally { setBusy(false); } }
  async function recent(client: any) { return client.stepUp({password:stepUp,...(stepCode.includes('-')?{recoveryCode:stepCode}:{...(stepCode?{totpCode:stepCode}:{})})}); }
  async function logout() { setBusy(true); setMessage(undefined); try { await logoutActiveCloudAccount(); router.back(); } catch (error) { if (!await hasActiveCloudAccount().catch(() => false)) router.back(); else setMessage(cloudMobileErrorMessage(error, zh)); } finally { setBusy(false); } }
  function confirmLogout() { Alert.alert(zh?'退出 Thandoff 账户？':'Sign out of Thandoff account?', zh?'这会移除该 Thandoff 账户添加到本设备的所有云端控制面板。手动添加的控制面板会保留。':'This removes every cloud Control Plane added by this Thandoff account from this device. Manually added Control Planes are kept.', [{text:zh?'取消':'Cancel',style:'cancel'},{text:zh?'退出':'Sign out',style:'destructive',onPress:()=>void logout()}]); }
  return <><Stack.Screen options={{ title: zh ? 'Thandoff 账户设置' : 'Thandoff account settings' }}/><Screen>
    <View style={styles.heading}><Text accessibilityRole="header" style={[styles.title,{color:colors.text}]}>{zh?'Thandoff 账户':'Thandoff account'}</Text><Text style={[styles.detail,{color:colors.textMuted}]}>{profile?.email ?? (zh?'正在加载 Thandoff 账户信息…':'Loading Thandoff account information…')}</Text></View>
    <Section title={zh?'账号信息':'Account information'} colors={colors}><View style={styles.row}><Text style={[styles.detail,styles.grow,{color:colors.textMuted}]}>{zh?'邮箱':'Email'}</Text><Text selectable style={[styles.label,{color:colors.text}]}>{profile?.email ?? '—'}</Text></View><View style={styles.row}><Text style={[styles.detail,styles.grow,{color:colors.textMuted}]}>{zh?'邮箱状态':'Email status'}</Text><Text style={[styles.label,{color:profile?.emailVerified?colors.sessionActive:colors.textMuted}]}>{profile?.emailVerified ? (zh?'已验证':'Verified') : (zh?'等待验证':'Pending')}</Text></View>{profile?.id?<View style={styles.row}><Text style={[styles.detail,styles.grow,{color:colors.textMuted}]}>{zh?'账号 ID':'Account ID'}</Text><Text numberOfLines={1} selectable style={[styles.accountId,{color:colors.text}]}>{profile.id}</Text></View>:null}</Section>
    <Section title={zh?'云端控制面板':'Cloud Control Planes'} colors={colors}><Text style={[styles.detail,{color:colors.textMuted}]}>{zh?'查看并添加已绑定到此 Thandoff 账户的控制面板。':'View and add Control Planes bound to this Thandoff account.'}</Text><NativeActionButton compact disabled={busy} label={zh?'管理云端控制面板':'Manage cloud Control Planes'} onPress={()=>router.push('/cloud-control-planes' as never)}/></Section>
    <Section title={zh?'登录设备':'Devices'} colors={colors}>{devices.map(device=><View key={device.id} style={styles.row}><View style={styles.grow}><Text style={[styles.label,{color:colors.text}]}>{device.deviceName ?? device.id}</Text><Text style={[styles.detail,{color:colors.textMuted}]}>{device.kind}{device.id===currentDeviceId?(zh?' · 当前设备':' · This device'):''}</Text></View>{device.id!==currentDeviceId?<Pressable accessibilityRole="button" disabled={busy} onPress={()=>void action(client=>client.revokeDevice(device.id))}><Text style={[styles.command,{color:colors.error}]}>{zh?'撤销':'Revoke'}</Text></Pressable>:null}</View>)}</Section>
    <Section title="TOTP" colors={colors}>{!enrollment&&!recoveryCodes.length?<View style={styles.actions}><NativeActionButton compact disabled={busy||Boolean(profile?.totpEnabled&&!stepUp)} label={profile?.totpEnabled?(zh?'替换身份验证器':'Replace authenticator'):(zh?'启用身份验证器':'Enable authenticator')} onPress={()=>void action(async client=>client.beginTotp(profile?.totpEnabled?{replace:true,stepUp:await recent(client)}:{}),setEnrollment)}/>{profile?.totpEnabled?<NativeActionButton compact destructive disabled={busy||!stepUp} label={zh?'关闭身份验证器':'Disable authenticator'} onPress={()=>void action(async client=>client.disableTotp({stepUp:await recent(client)}))}/>:null}</View>:null}{enrollment?<><Text selectable style={[styles.secret,{color:colors.text}]}>{enrollment.secret}</Text><OneTimeCodeInput accessibilityLabel="TOTP" disabled={busy} onChangeText={setTotpCode} value={totpCode}/><NativeActionButton compact disabled={busy||totpCode.length!==6} label={zh?'确认并生成恢复码':'Confirm and create recovery codes'} onPress={()=>void action(client=>client.confirmTotp({enrollmentToken:enrollment.enrollmentToken,code:totpCode}),result=>{setRecoveryCodes(result.recoveryCodes??[]);setEnrollment(undefined)})}/></>:null}{recoveryCodes.length?<><Text style={[styles.detail,{color:colors.textMuted}]}>{zh?'恢复码只显示一次，请存放在安全位置。':'Recovery codes are shown once. Store them securely.'}</Text><Text selectable style={[styles.secret,{color:colors.text}]}>{recoveryCodes.join('\n')}</Text></>:null}</Section>
    <Section title={zh?'登录方式':'Sign-in methods'} colors={colors}><TextInput accessibilityLabel={zh?'近期认证密码':'Recent authentication password'} onChangeText={setStepUp} placeholder={zh?'关联或解除前输入密码':'Password required to link or unlink'} placeholderTextColor={colors.textMuted} secureTextEntry style={[styles.input,{borderColor:colors.border,color:colors.text}]} value={stepUp}/><TextInput accessibilityLabel={zh?'身份验证器或恢复码':'Authenticator or recovery code'} autoCapitalize="characters" onChangeText={setStepCode} placeholder={zh?'身份验证器或恢复码（可选）':'Authenticator or recovery code (optional)'} placeholderTextColor={colors.textMuted} style={[styles.input,{borderColor:colors.border,color:colors.text}]} value={stepCode}/>{providers.map(provider=><View key={provider.id} style={styles.row}><Text style={[styles.label,styles.grow,{color:colors.text}]}>{typeof provider.displayName==='string'?provider.displayName:provider.displayName?.translations?.[locale]??provider.displayName?.default??provider.id}</Text><Pressable accessibilityRole="button" disabled={busy||provider.id==='email'||!stepUp} onPress={()=>void action(async client=>{const recent=await client.stepUp({password:stepUp,...(stepCode.includes('-')?{recoveryCode:stepCode}:{...(stepCode?{totpCode:stepCode}:{})})});if(provider.linked)return client.unlinkProvider(provider.id,{stepUp:recent});const result=await client.linkProvider(provider.id,{stepUp:recent,continuation:{redirectUri:'taskhandoff://cloud-provider/callback'}});if(result.authorizationUrl)await Linking.openURL(result.authorizationUrl);return result})}><Text style={[styles.command,{color:provider.id==='email'?colors.textMuted:colors.primary}]}>{provider.linked?(zh?'解除':'Unlink'):(zh?'关联':'Link')}</Text></Pressable></View>)}</Section>
    <Section title={zh?'修改密码':'Change password'} colors={colors}><TextInput accessibilityLabel={zh?'当前密码':'Current password'} onChangeText={setCurrentPassword} placeholder={zh?'当前密码':'Current password'} placeholderTextColor={colors.textMuted} secureTextEntry style={[styles.input,{borderColor:colors.border,color:colors.text}]} value={currentPassword}/><TextInput accessibilityLabel={zh?'新密码':'New password'} onChangeText={setNewPassword} placeholder={zh?'新密码（至少 12 位）':'New password (12+ characters)'} placeholderTextColor={colors.textMuted} secureTextEntry style={[styles.input,{borderColor:colors.border,color:colors.text}]} value={newPassword}/><NativeActionButton compact disabled={busy||!currentPassword||newPassword.length<12||!stepUp} label={zh?'更新密码':'Update password'} onPress={()=>void action(async client=>client.changePassword({currentPassword,newPassword,stepUp:await recent(client)}),()=>{setCurrentPassword('');setNewPassword('')})}/></Section>
    {message?<Text accessibilityLiveRegion="polite" style={[styles.message,{color:colors.error}]}>{message}</Text>:null}<Text style={[styles.detail,{color:colors.textMuted}]}>{zh?'退出后会移除此 Thandoff 账户添加的云端控制面板；手动添加的控制面板不会受影响。':'Signing out removes this Thandoff account’s cloud Control Planes. Manually added Control Planes are not affected.'}</Text><NativeActionButton destructive disabled={busy} label={zh?'退出 Thandoff 账户':'Sign out of Thandoff account'} onPress={confirmLogout}/>
  </Screen></>;
}

function Section({title,colors,children}:{title:string;colors:any;children:ReactNode}){return <View style={[styles.section,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text accessibilityRole="header" style={[styles.sectionTitle,{color:colors.text}]}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({heading:{gap:4},title:{fontSize:24,fontWeight:'700'},section:{borderRadius:8,borderWidth:StyleSheet.hairlineWidth,gap:12,padding:14},sectionTitle:{fontSize:17,fontWeight:'700'},row:{alignItems:'center',flexDirection:'row',gap:12,minHeight:40},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},grow:{flex:1},label:{fontSize:15,fontWeight:'600'},accountId:{fontFamily:'monospace',fontSize:12,maxWidth:'62%'},detail:{fontSize:13,lineHeight:19},command:{fontSize:14,fontWeight:'600'},input:{borderRadius:8,borderWidth:StyleSheet.hairlineWidth,fontSize:15,minHeight:46,paddingHorizontal:12},secret:{fontFamily:'monospace',fontSize:12,lineHeight:19},message:{fontSize:14,lineHeight:20}});
