import { z } from "zod";
import {
  NodeJoinInviteStatusSchema,
  NodeLocalFolderSchema,
  NodeFolderTreeEntrySchema,
  NodeRuntimeSchema,
  UpdateCheckResultSchema,
  UpdateJobSchema,
} from "@task-handoff/protocol/control-plane";
import { emptyInput, group, inputOf, looseOutput, type CliGroup, type CliLeaf } from "./definition.ts";
import { NODE_ADMIN_OUTPUT_SCHEMAS } from "../commands/node-admin.ts";
import {
  nodeCheck,
  nodeConnectionsCreate,
  nodeConnectionsList,
  nodeConnectionsRemove,
  nodeCreate,
  nodeDockerImages,
  nodeExternalListenerSet,
  nodeExternalListenerShow,
  nodeFoldersAdd,
  nodeFoldersList,
  nodeFoldersRemove,
  nodeFoldersTree,
  nodeFoldersUpdate,
  nodeImageOptions,
  nodeModelRelaySet,
  nodeModelRelayShow,
  nodePairingInvite,
  nodePairingsList,
  nodePairingsRemove,
  nodeRemove,
  nodeRuntimesCheck,
  nodeRuntimesCreate,
  nodeRuntimesList,
  nodeRuntimesRemove,
  nodeRuntimesUpdate,
  nodeSyncLocal,
  nodeUpdatesApply,
  nodeUpdatesCheck,
  nodeUpdatesJobs,
} from "../commands/node-admin.ts";
import { nodeJoinComplete, nodeJoinInvite, nodeJoinStatus } from "../commands/node-join.ts";

const nodeIdArg = { name: "nodeId", description: "Node ID", required: true };
const configOption = { flags: "--config <file>", description: "Request body as a JSON file (Control Plane wire body)" };

export const nodeExtraLeaves: readonly CliLeaf[] = [
  {
    id: "node create", group: "node", name: "create", stage: "B", write: true,
    summary: "Create a node record from a JSON request body",
    options: [configOption],
    input: inputOf({ config: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.nodeRemove,
    outputPinned: false,
    handler: nodeCreate,
  },
  {
    id: "node remove", group: "node", name: "remove", stage: "B", write: true,
    summary: "Remove a node and revoke its proxied pairing",
    args: [nodeIdArg],
    options: [{ flags: "--force", description: "Force removal when the node is still reachable" }],
    input: inputOf({ nodeId: z.string(), force: z.boolean().optional() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.nodeRemove,
    handler: nodeRemove,
  },
  {
    id: "node check", group: "node", name: "check", stage: "B",
    summary: "Probe a node's agent and report its health",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: z.looseObject({ id: z.string(), status: z.string(), checkedAt: z.string() }),
    outputPinned: false,
    handler: nodeCheck,
  },
  {
    id: "node sync-local", group: "node", name: "sync-local", stage: "B", write: true,
    summary: "Register or refresh the local node connection",
    input: emptyInput,
    output: looseOutput,
    outputPinned: false,
    handler: nodeSyncLocal,
  },
  {
    id: "node folders list", group: "node", name: "folders list", stage: "B",
    summary: "List the local folders a node exposes",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: z.array(NodeLocalFolderSchema),
    handler: nodeFoldersList,
  },
  {
    id: "node folders tree", group: "node", name: "folders tree", stage: "B",
    summary: "Show a node's local folder tree",
    args: [nodeIdArg],
    options: [
      { flags: "--path <path>", description: "Subtree root inside the node filesystem" },
      { flags: "--depth <depth>", description: "Maximum tree depth" },
    ],
    input: inputOf({ nodeId: z.string(), path: z.string().optional(), depth: z.string().optional() }),
    output: z.array(NodeFolderTreeEntrySchema),
    handler: nodeFoldersTree,
  },
  {
    id: "node folders add", group: "node", name: "folders add", stage: "B", write: true,
    summary: "Register a local folder on a node",
    args: [nodeIdArg],
    options: [configOption],
    input: inputOf({ nodeId: z.string(), config: z.string() }),
    output: NodeLocalFolderSchema,
    handler: nodeFoldersAdd,
  },
  {
    id: "node folders update", group: "node", name: "folders update", stage: "B", write: true,
    summary: "Update a node local folder",
    args: [nodeIdArg, { name: "folderId", description: "Local folder ID", required: true }],
    options: [configOption],
    input: inputOf({ nodeId: z.string(), folderId: z.string(), config: z.string() }),
    output: NodeLocalFolderSchema,
    handler: nodeFoldersUpdate,
  },
  {
    id: "node folders remove", group: "node", name: "folders remove", stage: "B", write: true,
    summary: "Remove a node local folder",
    args: [nodeIdArg, { name: "folderId", description: "Local folder ID", required: true }],
    input: inputOf({ nodeId: z.string(), folderId: z.string() }),
    output: z.looseObject({ deleted: z.boolean() }),
    outputPinned: false,
    handler: nodeFoldersRemove,
  },
  {
    id: "node runtimes list", group: "node", name: "runtimes list", stage: "B",
    summary: "List the container runtimes a node exposes",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: z.array(NodeRuntimeSchema),
    handler: nodeRuntimesList,
  },
  {
    id: "node runtimes create", group: "node", name: "runtimes create", stage: "B", write: true,
    summary: "Create a runtime on a node",
    args: [nodeIdArg],
    options: [configOption],
    input: inputOf({ nodeId: z.string(), config: z.string() }),
    output: NodeRuntimeSchema,
    handler: nodeRuntimesCreate,
  },
  {
    id: "node runtimes update", group: "node", name: "runtimes update", stage: "B", write: true,
    summary: "Update a node runtime",
    args: [nodeIdArg, { name: "runtimeId", description: "Runtime ID", required: true }],
    options: [configOption],
    input: inputOf({ nodeId: z.string(), runtimeId: z.string(), config: z.string() }),
    output: NodeRuntimeSchema,
    handler: nodeRuntimesUpdate,
  },
  {
    id: "node runtimes remove", group: "node", name: "runtimes remove", stage: "B", write: true,
    summary: "Remove a node runtime",
    args: [nodeIdArg, { name: "runtimeId", description: "Runtime ID", required: true }],
    input: inputOf({ nodeId: z.string(), runtimeId: z.string() }),
    output: z.looseObject({ deleted: z.boolean() }),
    outputPinned: false,
    handler: nodeRuntimesRemove,
  },
  {
    id: "node runtimes check", group: "node", name: "runtimes check", stage: "B",
    summary: "Probe a node runtime and report its health",
    args: [nodeIdArg, { name: "runtimeId", description: "Runtime ID", required: true }],
    input: inputOf({ nodeId: z.string(), runtimeId: z.string() }),
    output: NodeRuntimeSchema,
    outputPinned: false,
    handler: nodeRuntimesCheck,
  },
  {
    id: "node docker images", group: "node", name: "docker images", stage: "B",
    summary: "List docker images available on a node",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.dockerImages,
    outputPinned: false,
    handler: nodeDockerImages,
  },
  {
    id: "node image-options", group: "node", name: "image-options", stage: "B",
    summary: "List image options a node can provision",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.imageOptions,
    handler: nodeImageOptions,
  },
  {
    id: "node settings external-listener show", group: "node", name: "settings external-listener show", stage: "B",
    summary: "Show a node's external listener settings",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.externalListener,
    handler: nodeExternalListenerShow,
  },
  {
    id: "node settings external-listener set", group: "node", name: "settings external-listener set", stage: "B", write: true,
    summary: "Update a node's external listener settings",
    args: [nodeIdArg],
    options: [configOption],
    input: inputOf({ nodeId: z.string(), config: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.externalListener,
    handler: nodeExternalListenerSet,
  },
  {
    id: "node settings model-relay show", group: "node", name: "settings model-relay show", stage: "B",
    summary: "Show a node's model relay settings",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.modelRelay,
    handler: nodeModelRelayShow,
  },
  {
    id: "node settings model-relay set", group: "node", name: "settings model-relay set", stage: "B", write: true,
    summary: "Update a node's model relay settings",
    args: [nodeIdArg],
    options: [configOption],
    input: inputOf({ nodeId: z.string(), config: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.modelRelay,
    handler: nodeModelRelaySet,
  },
  {
    id: "node updates jobs", group: "node", name: "updates jobs", stage: "B",
    summary: "List node update jobs",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: z.array(UpdateJobSchema),
    handler: nodeUpdatesJobs,
  },
  {
    id: "node updates check", group: "node", name: "updates check", stage: "B",
    summary: "Check whether a node update is available",
    args: [nodeIdArg],
    options: [{ flags: "--config <file>", description: "Update check request JSON (optional)" }],
    input: inputOf({ nodeId: z.string(), config: z.string().optional() }),
    output: UpdateCheckResultSchema,
    handler: nodeUpdatesCheck,
  },
  {
    id: "node updates apply", group: "node", name: "updates apply", stage: "B", write: true,
    summary: "Apply a node update and optionally wait for it to finish",
    args: [nodeIdArg],
    options: [
      configOption,
      { flags: "--wait", description: "Poll the update job until it reaches a terminal state" },
    ],
    input: inputOf({ nodeId: z.string(), config: z.string(), wait: z.boolean().optional() }),
    output: UpdateJobSchema,
    handler: nodeUpdatesApply,
  },
  {
    id: "node pairing invite", group: "node", name: "pairing invite", stage: "B", write: true,
    summary: "Create a pairing invite token for a node",
    args: [nodeIdArg],
    options: [{ flags: "--config <file>", description: "Pairing invite request JSON (optional)" }],
    input: inputOf({ nodeId: z.string(), config: z.string().optional() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.pairingInvite,
    handler: nodePairingInvite,
  },
  {
    id: "node pairings list", group: "node", name: "pairings list", stage: "B",
    summary: "List the control plane pairings registered on a node",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.pairings,
    handler: nodePairingsList,
  },
  {
    id: "node pairings remove", group: "node", name: "pairings remove", stage: "B", write: true,
    summary: "Revoke a control plane pairing on a node",
    args: [nodeIdArg, { name: "keyId", description: "Pairing key ID", required: true }],
    input: inputOf({ nodeId: z.string(), keyId: z.string() }),
    output: z.looseObject({ deleted: z.boolean() }),
    outputPinned: false,
    handler: nodePairingsRemove,
  },
  {
    id: "node connections list", group: "node", name: "connections list", stage: "B",
    summary: "List the control plane connections configured on a node",
    args: [nodeIdArg],
    input: inputOf({ nodeId: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.connections,
    handler: nodeConnectionsList,
  },
  {
    id: "node connections create", group: "node", name: "connections create", stage: "B", write: true,
    summary: "Create a control plane connection on a node",
    args: [nodeIdArg],
    options: [configOption],
    input: inputOf({ nodeId: z.string(), config: z.string() }),
    output: NODE_ADMIN_OUTPUT_SCHEMAS.connectionCreate,
    handler: nodeConnectionsCreate,
  },
  {
    id: "node connections remove", group: "node", name: "connections remove", stage: "B", write: true,
    summary: "Remove a control plane connection from a node",
    args: [nodeIdArg, { name: "connectionId", description: "Connection ID", required: true }],
    input: inputOf({ nodeId: z.string(), connectionId: z.string() }),
    output: z.looseObject({ deleted: z.boolean() }),
    outputPinned: false,
    handler: nodeConnectionsRemove,
  },
];

export const nodeJoinGroup: CliGroup = group("node-join", "Join a node to the Control Plane", [
  {
    id: "node-join invite", group: "node-join", name: "invite", stage: "B", write: true,
    summary: "Create a node join invite token",
    options: [{ flags: "--config <file>", description: "Join invite request JSON (optional)" }],
    input: inputOf({ config: z.string().optional() }),
    output: z.looseObject({ id: z.string(), expiresAt: z.string(), joinToken: z.string().optional() }),
    handler: nodeJoinInvite,
  },
  {
    id: "node-join status", group: "node-join", name: "status", stage: "B",
    summary: "Show whether a node join invite was completed",
    args: [{ name: "inviteId", description: "Join invite ID", required: true }],
    input: inputOf({ inviteId: z.string() }),
    output: NodeJoinInviteStatusSchema,
    handler: nodeJoinStatus,
  },
  {
    id: "node-join complete", group: "node-join", name: "complete", stage: "B", write: true,
    summary: "Complete a node join from a JSON request body",
    options: [configOption],
    input: inputOf({ config: z.string() }),
    output: looseOutput,
    outputPinned: false,
    handler: nodeJoinComplete,
  },
]);
