plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.taskhandoffbrowser'
version = '0.0.1'

android {
  namespace 'expo.modules.taskhandoffbrowser'
}

dependencies {
  implementation 'androidx.webkit:webkit:1.15.0'
  implementation 'com.squareup.okhttp3:okhttp:4.12.0'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
}
