export const ANCHORED_SELECT_MENU_WIDTH = 300;
export const ANCHORED_SELECT_MENU_HORIZONTAL_PADDING = 16;
export const ANCHORED_SELECT_MENU_CONTENT_WIDTH = ANCHORED_SELECT_MENU_WIDTH - (ANCHORED_SELECT_MENU_HORIZONTAL_PADDING * 2);
