import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { Story } from '@task-handoff/protocol/stories';
import { AnchoredSelectMenu } from '../components/AnchoredSelectMenu';
import { SystemIcon } from '../components/SystemIcon';
import { useMobileTheme } from '../components/theme';
import { useMobileControlPlaneRuntime } from '../control-plane/use-mobile-control-plane-runtime';
import { useActiveDirectories } from '../directories/use-directories';
import { useI18n } from '../i18n';

export function StoryEditor({ storyId, nodeId, onSaved }: { storyId?: string; nodeId?: string; onSaved(story: Story): void }) {
  const { colors } = useMobileTheme(); const { t } = useI18n(); const runtime = useMobileControlPlaneRuntime(); const { state: directory } = useActiveDirectories();
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [ownerNodeId, setOwnerNodeId] = useState(nodeId || ''); const [story, setStory] = useState<Story>(); const [busy, setBusy] = useState(Boolean(storyId)); const [error, setError] = useState<string>();
  const nodes = useMemo(() => directory.nodes.filter((node) => node.connectionPhase !== 'offline'), [directory.nodes]);
  useEffect(() => { if (ownerNodeId || !nodes.length) return; setOwnerNodeId(nodes[0].id); }, [nodes, ownerNodeId]);
  useEffect(() => { if (!storyId || !nodeId || !runtime.api) return; let cancelled = false; setBusy(true); void runtime.api.stories.get(storyId, nodeId).then((value) => { if (!cancelled) { setStory(value); setTitle(value.title); setDescription(value.description || ''); } }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : String(cause)); }).finally(() => { if (!cancelled) setBusy(false); }); return () => { cancelled = true; }; }, [nodeId, runtime.api, storyId]);
  const save = async () => { if (!runtime.api || !title.trim() || !ownerNodeId) return; setBusy(true); setError(undefined); try { const saved = story ? await runtime.api.stories.update(story.id, story.ownerNodeId, { title: title.trim(), description: description.trim() || null }) : await runtime.api.stories.create(ownerNodeId, { title: title.trim(), description: description.trim() || undefined }); onSaved(saved); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
  const toggleArchive = async () => { if (!runtime.api || !story) return; setBusy(true); try { const saved = story.archivedAt ? await runtime.api.stories.restore(story.id, story.ownerNodeId) : await runtime.api.stories.archive(story.id, story.ownerNodeId); onSaved(saved); } catch (cause) { Alert.alert(t('stories.saveError'), cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
  if (busy && storyId && !story) return <ActivityIndicator accessibilityLabel={t('common.loading')} style={styles.loading} />;
  return <ScrollView automaticallyAdjustKeyboardInsets contentContainerStyle={[styles.content, { backgroundColor: colors.background }]} keyboardShouldPersistTaps="handled"><View style={styles.field}><Text style={[styles.label, { color: colors.text }]}>{t('stories.title')}</Text><TextInput autoFocus={!storyId} maxLength={240} onChangeText={setTitle} value={title} style={[styles.input, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.text }]} /></View><View style={styles.field}><Text style={[styles.label, { color: colors.text }]}>{t('stories.description')}</Text><TextInput maxLength={4000} multiline onChangeText={setDescription} value={description} style={[styles.input, styles.textarea, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.text }]} /></View>{!storyId ? <View style={styles.field}><Text style={[styles.label, { color: colors.text }]}>{t('stories.ownerNode')}</Text><AnchoredSelectMenu cancelLabel={t('common.cancel')} onSelect={setOwnerNodeId} options={nodes.map((node) => ({ value: node.id, label: node.name, description: node.id, systemImage: 'server.rack' }))} selectedValue={ownerNodeId} title={t('stories.ownerNode')}>{(onPress) => <Pressable onPress={onPress} style={[styles.selector, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.selectorText, { color: colors.text }]}>{nodes.find((node) => node.id === ownerNodeId)?.name || t('stories.selectNode')}</Text><SystemIcon android="arrow_drop_down" color={colors.textMuted} ios="chevron.down" size={17} /></Pressable>}</AnchoredSelectMenu></View> : null}{error ? <Text style={[styles.error, { color: colors.error }]}>{error}</Text> : null}<Pressable disabled={busy || !title.trim() || !ownerNodeId} onPress={() => { void save(); }} style={[styles.primary, { backgroundColor: colors.primary, opacity: busy || !title.trim() || !ownerNodeId ? 0.5 : 1 }]}><Text style={styles.primaryText}>{t('common.save')}</Text></Pressable>{story ? <Pressable disabled={busy} onPress={() => { void toggleArchive(); }} style={[styles.secondary, { borderColor: colors.border }]}><Text style={[styles.secondaryText, { color: colors.text }]}>{story.archivedAt ? t('stories.restore') : t('stories.archive')}</Text></Pressable> : null}</ScrollView>;
}
const styles = StyleSheet.create({ loading: { flex: 1 }, content: { gap: 18, padding: 16 }, field: { gap: 7 }, label: { fontSize: 14, fontWeight: '500' }, input: { borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, fontSize: 15, minHeight: 44, paddingHorizontal: 12 }, textarea: { minHeight: 110, paddingTop: 11, textAlignVertical: 'top' }, selector: { alignItems: 'center', borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', justifyContent: 'space-between', minHeight: 44, paddingHorizontal: 12 }, selectorText: { fontSize: 15 }, error: { fontSize: 14 }, primary: { alignItems: 'center', borderRadius: 10, justifyContent: 'center', minHeight: 46 }, primaryText: { color: '#fff', fontSize: 15, fontWeight: '600' }, secondary: { alignItems: 'center', borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, justifyContent: 'center', minHeight: 46 }, secondaryText: { fontSize: 15 } });
