import hljs from "highlight.js/lib/core";
import bash from "highlight.js/lib/languages/bash";
import cpp from "highlight.js/lib/languages/cpp";
import csharp from "highlight.js/lib/languages/csharp";
import css from "highlight.js/lib/languages/css";
import dockerfile from "highlight.js/lib/languages/dockerfile";
import go from "highlight.js/lib/languages/go";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import kotlin from "highlight.js/lib/languages/kotlin";
import markdown from "highlight.js/lib/languages/markdown";
import php from "highlight.js/lib/languages/php";
import python from "highlight.js/lib/languages/python";
import ruby from "highlight.js/lib/languages/ruby";
import rust from "highlight.js/lib/languages/rust";
import sql from "highlight.js/lib/languages/sql";
import swift from "highlight.js/lib/languages/swift";
import typescript from "highlight.js/lib/languages/typescript";
import xml from "highlight.js/lib/languages/xml";
import yaml from "highlight.js/lib/languages/yaml";
import { Renderer, marked } from "marked";
import markedKatex from "marked-katex-extension";

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const renderer = new Renderer();

const languages = {
  bash,
  cpp,
  csharp,
  css,
  dockerfile,
  go,
  java,
  javascript,
  json,
  kotlin,
  markdown,
  php,
  python,
  ruby,
  rust,
  sql,
  swift,
  typescript,
  xml,
  yaml,
};

for (const [name, language] of Object.entries(languages)) {
  hljs.registerLanguage(name, language);
}

// Raw HTML is displayed as source. This keeps session content untrusted while
// still allowing every Markdown construct generated by marked.
renderer.html = ({ text }) => escapeHtml(text);
renderer.table = function (token) {
  const table = Reflect.apply(Renderer.prototype.table, this, [token]);
  return `<div class="markdown-table-wrapper">${table}</div>\n`;
};
export function renderCodeBlock(value: unknown, language?: unknown) {
  const text = String(value ?? "");
  const requestedLanguage = String(language ?? "").trim().split(/\s+/, 1)[0].toLowerCase();
  if (requestedLanguage === "mermaid") {
    return `<div class="markdown-mermaid" data-mermaid-state="pending"><pre><code>${escapeHtml(text)}</code></pre></div>\n`;
  }
  if (!requestedLanguage || !hljs.getLanguage(requestedLanguage)) {
    return `<pre><code>${escapeHtml(text)}</code></pre>\n`;
  }
  const highlighted = hljs.highlight(text, {
    language: requestedLanguage,
    ignoreIllegals: true,
  }).value;
  return `<pre><code class="hljs language-${escapeHtml(requestedLanguage)}">${highlighted}</code></pre>\n`;
}

renderer.code = ({ text, lang }) => renderCodeBlock(text, lang);

marked.use(markedKatex({
  nonStandard: true,
  strict: "warn",
  throwOnError: false,
}));

marked.use({
  async: false,
  breaks: true,
  gfm: true,
  renderer,
});

export function renderMarkdown(value: unknown) {
  const source = String(value ?? "").replace(/\r\n?/g, "\n").trim();
  return source ? marked.parse(source, { async: false }) as string : "";
}
