import hljs from "highlight.js/lib/core";
import bash from "highlight.js/lib/languages/bash";
import cpp from "highlight.js/lib/languages/cpp";
import csharp from "highlight.js/lib/languages/csharp";
import css from "highlight.js/lib/languages/css";
import dockerfile from "highlight.js/lib/languages/dockerfile";
import go from "highlight.js/lib/languages/go";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import kotlin from "highlight.js/lib/languages/kotlin";
import markdown from "highlight.js/lib/languages/markdown";
import php from "highlight.js/lib/languages/php";
import python from "highlight.js/lib/languages/python";
import ruby from "highlight.js/lib/languages/ruby";
import rust from "highlight.js/lib/languages/rust";
import sql from "highlight.js/lib/languages/sql";
import swift from "highlight.js/lib/languages/swift";
import typescript from "highlight.js/lib/languages/typescript";
import xml from "highlight.js/lib/languages/xml";
import yaml from "highlight.js/lib/languages/yaml";
import { Renderer, marked } from "marked";
import markedKatex from "marked-katex-extension";

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export type MarkdownCodeTools = {
  copiedLabel: string;
  copyLabel: string;
  plainTextLabel: string;
};

export type MarkdownRenderOptions = {
  codeTools?: MarkdownCodeTools;
};

const languages = {
  bash,
  cpp,
  csharp,
  css,
  dockerfile,
  go,
  java,
  javascript,
  json,
  kotlin,
  markdown,
  php,
  python,
  ruby,
  rust,
  sql,
  swift,
  typescript,
  xml,
  yaml,
};

for (const [name, language] of Object.entries(languages)) {
  hljs.registerLanguage(name, language);
}

function renderCodeTools(language: string, tools?: MarkdownCodeTools) {
  if (!tools) return undefined;
  const label = language || tools.plainTextLabel;
  return `<div class="markdown-code-toolbar"><span class="markdown-code-language">${escapeHtml(label)}</span><button type="button" class="markdown-code-copy" aria-label="${escapeHtml(tools.copyLabel)}" data-copy-label="${escapeHtml(tools.copyLabel)}" data-copied-label="${escapeHtml(tools.copiedLabel)}">${escapeHtml(tools.copyLabel)}</button></div>`;
}

export function renderCodeBlock(value: unknown, language?: unknown, tools?: MarkdownCodeTools) {
  const text = String(value ?? "");
  const requestedLanguage = String(language ?? "").trim().split(/\s+/, 1)[0].toLowerCase();
  if (requestedLanguage === "mermaid") {
    return `<div class="markdown-mermaid" data-mermaid-state="pending"><pre><code>${escapeHtml(text)}</code></pre></div>\n`;
  }
  const toolbar = renderCodeTools(requestedLanguage, tools);
  const open = toolbar ? `<div class="markdown-code-block">${toolbar}` : "";
  const close = toolbar ? "</div>" : "";
  const languageAttribute = requestedLanguage ? ` data-language="${escapeHtml(requestedLanguage)}"` : "";
  if (!requestedLanguage || !hljs.getLanguage(requestedLanguage)) {
    return `${open}<pre${languageAttribute}><code>${escapeHtml(text)}</code></pre>${close}\n`;
  }
  const highlighted = highlightSource(text, requestedLanguage);
  return `${open}<pre${languageAttribute}><code class="hljs language-${escapeHtml(requestedLanguage)}">${highlighted}</code></pre>${close}\n`;
}

export function highlightSource(value: unknown, language?: unknown) {
  const text = String(value ?? "");
  const requestedLanguage = String(language ?? "").trim().toLowerCase();
  if (!requestedLanguage || !hljs.getLanguage(requestedLanguage)) return escapeHtml(text);
  return hljs.highlight(text, { language: requestedLanguage, ignoreIllegals: true }).value;
}

function createRenderer(options: MarkdownRenderOptions = {}) {
  const renderer = new Renderer();
  // Raw HTML is displayed as source. This keeps session content untrusted while
  // still allowing every Markdown construct generated by marked.
  renderer.html = ({ text }) => escapeHtml(text);
  renderer.table = function (token) {
    const table = Reflect.apply(Renderer.prototype.table, this, [token]);
    return `<div class="markdown-table-wrapper">${table}</div>\n`;
  };
  renderer.code = ({ text, lang }) => renderCodeBlock(text, lang, options.codeTools);
  return renderer;
}

marked.use(markedKatex({
  nonStandard: true,
  strict: "warn",
  throwOnError: false,
}));

marked.use({
  async: false,
  breaks: true,
  gfm: true,
});

export function renderMarkdown(value: unknown, options: MarkdownRenderOptions = {}) {
  const source = String(value ?? "").replace(/\r\n?/g, "\n").trim();
  return source ? marked.parse(source, { async: false, renderer: createRenderer(options) }) as string : "";
}

const copyResetTimers = new WeakMap<HTMLButtonElement, ReturnType<typeof setTimeout>>();

export async function handleMarkdownCodeCopy(event: Event) {
  const button = event.target instanceof Element ? event.target.closest<HTMLButtonElement>(".markdown-code-copy") : undefined;
  if (!button) return false;
  const code = button.closest(".markdown-code-block")?.querySelector("pre code")?.textContent;
  if (code === undefined || typeof navigator === "undefined" || !navigator.clipboard?.writeText) return false;
  try {
    await navigator.clipboard.writeText(code);
  } catch {
    return false;
  }
  const copyLabel = button.dataset.copyLabel || button.textContent || "";
  const copiedLabel = button.dataset.copiedLabel || copyLabel;
  button.textContent = copiedLabel;
  button.setAttribute("aria-label", copiedLabel);
  const previousTimer = copyResetTimers.get(button);
  if (previousTimer) clearTimeout(previousTimer);
  copyResetTimers.set(button, setTimeout(() => {
    if (!button.isConnected) return;
    button.textContent = copyLabel;
    button.setAttribute("aria-label", copyLabel);
    copyResetTimers.delete(button);
  }, 1600));
  return true;
}
