export const SESSION_COMPOSER_EXPANDED_RADIUS = 22;
export const SESSION_COMPOSER_ACTION_SIZE = 38;
export const SESSION_COMPOSER_ACTION_RADIUS = SESSION_COMPOSER_ACTION_SIZE / 2;
export const SESSION_COMPOSER_ACTION_ICON_SIZE = 17;
export const SESSION_COMPOSER_TOOLBAR_HEIGHT = 56;
