import type { AiSessionPermissionMode } from '@task-handoff/protocol/ai-sessions';

export const SESSION_COMPOSER_EXPANDED_RADIUS = 22;
export const SESSION_COMPOSER_COLLAPSED_HEIGHT = 56;
export const SESSION_COMPOSER_EXPANDED_HEIGHT = 152;
export const SESSION_COMPOSER_ACTION_SIZE = 38;
export const SESSION_COMPOSER_ACTION_RADIUS = SESSION_COMPOSER_ACTION_SIZE / 2;
export const SESSION_COMPOSER_ACTION_ICON_SIZE = 17;
export const SESSION_COMPOSER_TOOLBAR_HEIGHT = 56;
export const SESSION_COMPOSER_TOOL_SIZE = 40;
export const SESSION_COMPOSER_ATTACHMENT_ICON_SIZE = 25;
export const SESSION_COMPOSER_MODEL_MAX_WIDTH = 120;
export const SESSION_COMPOSER_TRAILING_TOOL_GAP = 4;
export const SESSION_COMPOSER_COLLAPSED_INPUT_RIGHT = 52;
export const SESSION_COMPOSER_PERMISSION_HEIGHT = 38;
export const SESSION_COMPOSER_PERMISSION_RADIUS = SESSION_COMPOSER_PERMISSION_HEIGHT / 2;
export const SESSION_COMPOSER_PERMISSION_ICON_SLOT_SIZE = 20;
export const SESSION_COMPOSER_PERMISSION_ICON_LEFT = 8;
export const SESSION_COMPOSER_PERMISSION_TEXT_LEFT = 34;
export const SESSION_COMPOSER_PERMISSION_TEXT_RIGHT = 24;
export const SESSION_COMPOSER_PERMISSION_CHEVRON_RIGHT = 8;
export const SESSION_COMPOSER_PERMISSION_CHEVRON_SIZE = 10;
export const SESSION_COMPOSER_PERMISSION_WIDTH_OVERHEAD = 58;

export function sessionComposerCollapsedInputRight(modelControlsVisible: boolean) {
  return SESSION_COMPOSER_COLLAPSED_INPUT_RIGHT
    + (modelControlsVisible ? SESSION_COMPOSER_MODEL_MAX_WIDTH + SESSION_COMPOSER_TRAILING_TOOL_GAP : 0);
}

export function sessionComposerPermissionIconSize(mode: AiSessionPermissionMode) {
  return mode === 'ask' ? 21 : 22;
}
